#!/usr/bin/env python3
# BEACON-01 -- full working version (restored from PDF)
import json
import os
import sys
from datetime import date

CFG = "beacon.json"

DEFAULTS = {
    "name": "aerocement",
    "tagline": "Lightweight foamed concrete with alkali-resistant fiber, mixable with a drill and a bucket.",
    "description": "AR-GFRC aerocement: open-source foamed concrete targeting >=3 MPa compressive / >=1.5 MPa flexural at <=1000 kg/m3, load-matched to single-story walls. Failures are documented on purpose.",
    "version": "0.1.0",
    "gh_owner": "jesseray718",
    "gh_repo": "aerocement",
    "repo_url": "https://github.com/jesseray718/aerocement",
    "docs_url": "https://github.com/jesseray718/aerocement#readme",
    "bom_url": "https://github.com/jesseray718/aerocement/blob/main/BOM.md",
    "instructions_url": "https://github.com/jesseray718/aerocement/blob/main/BUILD.md",
    "philosophy_url": "PHILOSOPHY.md",
    "doi": "10.5281/zenodo.20639511",
    "image": "",
    "intended_use": "Low-cost, owner-built single-story walls and small structures in resource-constrained settings.",
    "development_stage": "prototype",
    "repo_description": "Open-source lightweight foamed concrete (AR-GFRC) for single-story walls. Drill-and-bucket buildable.",
    "topics": ["appropriate-technology", "open-source-hardware", "foamed-concrete", "gfrc", "permaculture", "off-grid", "construction-materials"],
    "keywords": ["aerocement", "foamed concrete", "AR-GFRC", "appropriate technology", "open hardware", "cellular concrete", "natural building"],
    "licenses": {"hardware": "CC-BY-SA-4.0", "documentation": "CC-BY-SA-4.0", "software": "GPL-3.0-or-later"},
    "licensor": {"name": "Jesse McMillen", "email": "jrm8908@proton.me", "affiliation": "One Human Family / OpenRoot"},
    "health_safety": "Cement is caustic: wear gloves and eye protection. Cut glass fiber irritates skin and lungs: wear a mask when handling dry fiber. Test batches only; no structural use until independently validated.",
    "validated": [
        "Fiber content must stay <=1.5% to avoid foam collapse",
        "E-glass degrades in alkali; use zirconia (AR) or basalt fiber",
        "Low elastic modulus: suspended spans are impractical"
    ],
    "theoretical": [
        ">=3 MPa compressive at <=1000 kg/m3 (target, not yet measured)",
        ">=1.5 MPa flexural at <=1000 kg/m3 (target, not yet measured)"
    ],
    "known_errors": [{
        "id": "H-003-RAD-10X",
        "title": "H-003 radiative-capture headline overstated \~10x (likely decimal/units error)",
        "summary": "The published H-003 thermal cascade headline figure for radiative capture appears inflated by roughly one order of magnitude due to a decimal or units slip. The physically realistic ceiling is far lower.",
        "resolution": "A 1-2 m2 instrumented test at Sikeston climate per the three written protocols, with raw data published win or lose. Until then: do not cite the headline number anywhere.",
        "status": "open"
    }]
}

def load():
    if not os.path.exists(CFG):
        cfg = json.loads(json.dumps(DEFAULTS))
        save(cfg)
        return cfg
    with open(CFG, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    for k, v in DEFAULTS.items():
        cfg.setdefault(k, v)
    return cfg

def save(cfg):
    with open(CFG, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2, ensure_ascii=False)
        f.write("\n")

def write(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s" % path)

def q(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'

def cmd_init():
    cfg = json.loads(json.dumps(DEFAULTS))
    save(cfg)
    print("Beacon initialized")

def cmd_okh(cfg):
    today = date.today().isoformat()
    L = []
    a = L.append
    a("# Open Know-How manifest -- generated by BEACON-01")
    a("okh-manifest-version: 1.0.0")
    a("date-created: %s" % today)
    a("date-updated: %s" % today)
    a("title: %s" % q(cfg["name"]))
    a("description: %s" % q(cfg["description"]))
    a("intended-use: %s" % q(cfg["intended_use"]))
    a("keywords:")
    for k in cfg["keywords"]:
        a("  - %s" % q(k))
    a("project-link: %s" % q(cfg["repo_url"]))
    if cfg.get("image"):
        a("image: %s" % q(cfg["image"]))
    a("made: false")
    a("made-independently: false")
    a("development-stage: %s" % q(cfg["development_stage"]))
    a("license:")
    a("  hardware: %s" % q(cfg["licenses"]["hardware"]))
    a("  documentation: %s" % q(cfg["licenses"]["documentation"]))
    a("  software: %s" % q(cfg["licenses"]["software"]))
    a("licensor:")
    a("  name: %s" % q(cfg["licensor"]["name"]))
    a("  email: %s" % q(cfg["licensor"]["email"]))
    a("  affiliation: %s" % q(cfg["licensor"]["affiliation"]))
    a("manifest-author:")
    a("  name: %s" % q(cfg["licensor"]["name"]))
    a("  email: %s" % q(cfg["licensor"]["email"]))
    a("documentation-home: %s" % q(cfg["docs_url"]))
    a("bom: %s" % q(cfg["bom_url"]))
    a("making-instructions:")
    a("  - path: %s" % q(cfg["instructions_url"]))
    a("    title: %s" % q("Build instructions"))
    a("design-files:")
    a("  - path: %s" % q(cfg["repo_url"]))
    a("    title: %s" % q("Source repository"))
    a("health-safety-notice: %s" % q(cfg["health_safety"]))
    write("okh.yml", "\n".join(L) + "\n")

def cmd_wiki(cfg):
    L = []
    a = L.append
    a("'''%s''' is %s" % (cfg["name"], cfg["tagline"][0].lower() + cfg["tagline"][1:]))
    a("")
    a(cfg["description"])
    a("")
    a("== Status ==")
    a("Development stage: '''%s'''. This project documents failures and open errors publicly, on purpose (falsification-first)." % cfg["development_stage"])
    a("")
    a("== What is validated vs. what is theoretical ==")
    a("''Validated by experiment or established materials science:''")
    for v in cfg["validated"]:
        a("* " + v)
    a("")
    a("''Targets not yet physically validated -- do not cite as results:''")
    for t in cfg["theoretical"]:
        a("* " + t)
    a("")
    if cfg["known_errors"]:
        a("== Known errors (open) ==")
        for e in cfg["known_errors"]:
            if e.get("status") == "open":
                a("* '''%s''' -- %s" % (e["title"], e["summary"]))
        a("")
    a("== Build one ==")
    a("# Read the bill of materials: %s" % cfg["bom_url"])
    a("# Mix a 1-liter test batch and record your ratios.")
    a("# Post a photo and your ratios in the project's GitHub Discussions -- an independent test batch is the single most valuable contribution right now.")
    a("")
    a("== Safety ==")
    a(cfg["health_safety"])
    a("")
    a("== Licensing ==")
    a("* Hardware designs: %s" % cfg["licenses"]["hardware"])
    a("* Documentation: %s" % cfg["licenses"]["documentation"])
    a("* Software: %s" % cfg["licenses"]["software"])
    a("Copyright is attributed to \"One Human Family\". Zero patents; the design is born free.")
    a("")
    a("== Links ==")
    a("* Source repository: %s" % cfg["repo_url"])
    if cfg.get("doi"):
        a("* Archived record (DOI): https://doi.org/%s" % cfg["doi"])
    a("")
    a("[[Category:Appropriate technology]]")
    a("[[Category:Construction]]")
    a("[[Category:Building materials]]")
    a("[[Category:Open source hardware]]")
    write("APPROPEDIA.wikitext", "\n".join(L) + "\n")

def cmd_issue(cfg):
    if not cfg["known_errors"]:
        return
    for e in cfg["known_errors"]:
        L = []
        a = L.append
        a("# KNOWN ERROR: %s -- do not cite until resolved" % e["title"])
        a("")
        a("**Status:** %s" % e.get("status", "open"))
        a("**ID:** %s" % e["id"])
        a("")
        a("## What is wrong")
        a(e["summary"])
        a("")
        a("## Why this issue stays pinned and public")
        a("This project is falsification-first. A named, visible error is a trust signal; a quietly corrected one is a landmine.")
        a("")
        a("## What resolves it")
        a(e["resolution"])
        a("")
        a("*Generated by BEACON-01. Pin this issue in the repo.*")
        path = "KNOWN_ERROR_%s.md" % e["id"].replace("/", "-")
        write(path, "\n".join(L) + "\n")

def cmd_readme(cfg):
    L = []
    a = L.append
    a("# %s" % cfg["name"])
    a("")
    a(cfg["tagline"])
    a("")
    a(cfg["description"])
    a("")
    a("**Status:** %s. Targets are not yet physically validated. Known errors are pinned and public on purpose -- see the issues tab." % cfg["development_stage"])
    a("")
    a("## Build one (small test batch)")
    a("")
    a("1. Read the bill of materials: %s" % cfg["bom_url"])
    a("2. Mix a 1-liter test batch; record your ratios and results.")
    a("3. Post a photo + ratios in Discussions. An independent test batch is the most valuable contribution this project can receive today.")
    a("")
    a("## Safety")
    a("")
    a(cfg["health_safety"])
    a("")
    a("---")
    a("*Why we do this: [PHILOSOPHY](%s) -- engineering first, philosophy one click away.*" % cfg["philosophy_url"])
    write("README_TOPFOLD.md", "\n".join(L) + "\n")

def cmd_topics(cfg):
    owner, repo = cfg["gh_owner"], cfg["gh_repo"]
    L = []
    a = L.append
    a("#!/data/data/com.termux/files/usr/bin/bash")
    a("# Generated by BEACON-01. REVIEW BEFORE RUNNING.")
    a("set -e")
    a("")
    a("# Option A: GitHub CLI")
    gh = "gh repo edit %s/%s --description %s" % (owner, repo, json.dumps(cfg["repo_description"]))
    for t in cfg["topics"]:
        gh += " --add-topic %s" % t
    a(gh)
    a("")
    a("# Option B: raw API (uncomment and export GITHUB_TOKEN first)")
    a("# curl ... (omitted for brevity)")
    write("topics.sh", "\n".join(L) + "\n")
    try:
        os.chmod("topics.sh", 0o755)
    except:
        pass

def cmd_all():
    cfg = load()
    cmd_okh(cfg)
    cmd_wiki(cfg)
    cmd_issue(cfg)
    cmd_readme(cfg)
    cmd_topics(cfg)
    print("Running all beacons")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        if sys.argv[1] == "init":
            cmd_init()
        elif sys.argv[1] == "all":
            cmd_all()
        else:
            print("Usage: python3 beacon.py {init|all}")
    else:
        print("Usage: python3 beacon.py {init|all}")
