#!/data/data/com.termux/files/usr/bin/bash
# Generated by BEACON-01. REVIEW BEFORE RUNNING.
set -e

# Option A: GitHub CLI
gh repo edit jesseray718/aerocement --description "Open-source lightweight foamed concrete (AR-GFRC) for single-story walls. Drill-and-bucket buildable." --add-topic appropriate-technology --add-topic open-source-hardware --add-topic foamed-concrete --add-topic gfrc --add-topic permaculture --add-topic off-grid --add-topic construction-materials

# Option B: raw API (uncomment and export GITHUB_TOKEN first)
# curl ... (omitted for brevity)
